---

- hosts: all
  become: true
  pre_tasks:

  - name: Dpkg fixing in Ubuntu Servers
    shell: dpkg --configure -a

  - name: Update and Upgrade remote in Ubuntu servers
    apt:
      update_cache: yes
      upgrade: yes

- hosts: controller
  become: true
  roles:
    - NTP
    - OPENSTACK
    - SQL
    - MSGQ
    - MEMCACHED
    - ETCD
